### ISSUE TITLE
[FEATURE REQUEST] SOCKET - Auto Reconnection

### ISSUE THREAD

**Issue by go4cas** [ov-studio/vNetworkify#4]
Allow clients to auto-reconnect after a break in connection.

This should include:
- Ping/Heartbeats
- Events for: `ping`, `reconnect_attempt`, `reconnect` and `reconnect_error` (similar to how socket.io implements this)
- Configuration of number reconnection attempts and time between attempts

**Comment by Aviril** [comment]
> Configuration of number reconnection attempts and time between attempts

Implemented: https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-vnetworkifysocketcreate-shared

> Events for: reconnect_attempt, reconnect and reconnect_error (similar to how socket.io implements this)

- Added parameter `reason` for [`socket.onClientDisconnect`](https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-socketonclientdisconnect-shared).

- Added Event: [`socket.onClientReconnect`](https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-socketonclientreconnect-client) to track every reconnection attempt.

- There is no need of separate `reconnect_attempt` since `currentAttempt` & `maxAttempts` are passed to `socket.onClientReconnect` as parameters.
- There is actually no need of separate `reconnect_error` either since `socket.onClientError` could be reused for such purpose.

**Comment by OvileAmriam** [comment]
Add support for infinite reconnection attempt. Would be apps that don't want to enforce manual reconnections.
Dynamically identify it when `attempts` is set to `-1`
```js
options: {
  reconnection: {
    attempts: -1, // Infinite attempts
    interval: 1000 // Duration in 'ms' b/w each attempt
  }
}
```

**Comment by OvileAmriam** [comment]
+ By default reconnection should be infinite unless otherwise specified by user.

**Comment by Aviril** [comment]
> Add support for infinite reconnection attempt. Would be useful for apps that don't want to enforce manual reconnections. Dynamically identify it when `attempts` is set to `-1`
> 
> ```js
> options: {
>   reconnection: {
>     attempts: -1, // Infinite attempts
>     interval: 1000 // Duration in 'ms' b/w each attempt
>   }
> }
> ```

Implemented: https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-vnetworkifysocketcreate-shared



> * By default reconnection should be infinite unless otherwise specified by user.

Considered, by default the reconnection settings are set to:
```js
// Client Options:
options: {
  reconnection: {
    attempts: -1, // Number of attempts before onClientDisconnect is reached. [Note: -1 = infinite attempts]
    interval: 2500 // Duration in 'ms' b/w each attempt
  }
}
```

**Comment by Aviril** [comment]
- Added Server-Event: [`socket.onServerConnect`](https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-socketonserverconnect-server).
- Added Server-Event: [`socket.onServerDisconnect`](https://github.com/ov-studio/vNetworkify/wiki/Module:-Socket-API#-socketonserverdisconnect-server).
